package com.weitzel.trustychain.model;

import com.weitzel.trustychain.chain.ProductChain;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

class ProductChainTest {

    @Test
    @DisplayName("Should create ProductChain with constructor")
    void shouldCreateProductChainWithConstructor() {
        LocalDateTime now = LocalDateTime.now();
        ProductChain chain = new ProductChain(
                "Actor", "PROD-001", "CREATE", "metadata",
                null, "signature", "publicKey", "hash123",
                now, "timestampSig");

        assertEquals("Actor", chain.getActor());
        assertEquals("PROD-001", chain.getProductCode());
        assertEquals("CREATE", chain.getEventType());
        assertEquals("metadata", chain.getMetadata());
        assertNull(chain.getPreviousHash());
        assertEquals("signature", chain.getSignature());
        assertEquals("publicKey", chain.getPublicKeySnapshot());
        assertEquals("hash123", chain.getCurrentHash());
        assertEquals(now, chain.getTrustedTimestamp());
        assertEquals("timestampSig", chain.getTimestampSignature());
    }

    @Test
    @DisplayName("Should set and get all fields")
    void shouldSetAndGetAllFields() {
        ProductChain chain = new ProductChain();
        LocalDateTime now = LocalDateTime.now();

        chain.setActor("New Actor");
        chain.setProductCode("NEW-PROD");
        chain.setEventType("UPDATE");
        chain.setMetadata("new metadata");
        chain.setPreviousHash("prevHash");
        chain.setSignature("newSig");
        chain.setPublicKeySnapshot("newKey");
        chain.setCurrentHash("newHash");
        chain.setTrustedTimestamp(now);
        chain.setTimestampSignature("newTsSig");
        chain.setCreatedAt(now);

        assertEquals("New Actor", chain.getActor());
        assertEquals("NEW-PROD", chain.getProductCode());
        assertEquals("UPDATE", chain.getEventType());
        assertEquals("new metadata", chain.getMetadata());
        assertEquals("prevHash", chain.getPreviousHash());
        assertEquals("newSig", chain.getSignature());
        assertEquals("newKey", chain.getPublicKeySnapshot());
        assertEquals("newHash", chain.getCurrentHash());
        assertEquals(now, chain.getTrustedTimestamp());
        assertEquals("newTsSig", chain.getTimestampSignature());
        assertEquals(now, chain.getCreatedAt());
    }

    @Test
    @DisplayName("Should get ID")
    void shouldGetId() {
        ProductChain chain = new ProductChain();
        assertNull(chain.getId()); // ID is generated by database
    }

    @Test
    @DisplayName("Should use NoArgsConstructor")
    void shouldUseNoArgsConstructor() {
        ProductChain chain = new ProductChain();
        assertNotNull(chain);
    }

    @Test
    @DisplayName("Should handle null metadata")
    void shouldHandleNullMetadata() {
        ProductChain chain = new ProductChain();
        chain.setMetadata(null);
        assertNull(chain.getMetadata());
    }

    @Test
    @DisplayName("Should handle empty strings")
    void shouldHandleEmptyStrings() {
        ProductChain chain = new ProductChain();
        chain.setActor("");
        chain.setProductCode("");
        assertEquals("", chain.getActor());
        assertEquals("", chain.getProductCode());
    }
}
